// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzuotnzbazewnqidrhsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6dW90bnpiYXpld25xaWRyaHNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzQ4NzcsImV4cCI6MjA3MzQxMDg3N30.q_CrTdOenJrqXcooKA70BkS1SVd3eoVoTFDdiSVZg0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});